[package]
name = "electrs_chain"
version = "0.9.0"
authors = ["Roman Zeyde <me@romanzey.de>"]
edition = "2018"

[dependencies]
anyhow = "1.0"
bitcoin = { version = "0.26", features = ["use-serde", "rand"] }
log = "0.4"
